package com.example.jobportal.dao; // Note the package is DAO

import com.example.jobportal.exceptions.UserNotFoundException;
import com.example.jobportal.model.Employer;
import com.example.jobportal.model.JobSeeker;
import com.example.jobportal.model.User;
import java.sql.*;

public class UserDAO {
    
    // --- Login Validation (Using Custom Exception) ---
    public static User validateUser(String username, String password) throws UserNotFoundException, SQLException {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            con = DBUtil.getConnection();
            ps = con.prepareStatement(
                "SELECT id, email, role FROM users WHERE username=? AND password=?"
            );
            ps.setString(1, username);
            ps.setString(2, password);
            rs = ps.executeQuery();
            
            if(rs.next()) {
                int id = rs.getInt("id");
                String email = rs.getString("email");
                String role = rs.getString("role");

                // Get role-specific details
                if("employer".equals(role)) {
                    PreparedStatement psDetails = con.prepareStatement("SELECT company_name FROM employers WHERE user_id=?");
                    psDetails.setInt(1, id);
                    ResultSet rsDetails = psDetails.executeQuery();
                    if(rsDetails.next()) {
                        String companyName = rsDetails.getString("company_name");
                        return new Employer(id, username, password, email, companyName);
                    }
                } else if("jobseeker".equals(role)) {
                    PreparedStatement psDetails = con.prepareStatement("SELECT resume FROM jobseekers WHERE user_id=?");
                    psDetails.setInt(1, id);
                    ResultSet rsDetails = psDetails.executeQuery();
                    if(rsDetails.next()) {
                        String resume = rsDetails.getString("resume");
                        return new JobSeeker(id, username, password, email, resume);
                    }
                }
                // Fallback for user found but details missing
                return null; 
            } else {
                // Throw custom exception if user is not found
                throw new UserNotFoundException("Invalid username or password.");
            }
        } finally {
            // Close resources: crucial for JDBC resource management
            try { if (rs != null) rs.close(); } catch (SQLException e) { /* ignore */ }
            try { if (ps != null) ps.close(); } catch (SQLException e) { /* ignore */ }
            try { if (con != null) con.close(); } catch (SQLException e) { /* ignore */ }
        }
    }

    // --- Registration (Using JDBC Transaction Handling) ---
    public static boolean registerUser(User user, String detail) throws SQLException {
        Connection con = null;
        PreparedStatement ps1 = null;
        PreparedStatement ps2 = null;

        try {
            con = DBUtil.getConnection();
            con.setAutoCommit(false); // **START TRANSACTION**

            // 1. Insert into USERS table
            ps1 = con.prepareStatement(
                "INSERT INTO users (username, password, email, role) VALUES (?, ?, ?, ?)",
                Statement.RETURN_GENERATED_KEYS 
            );
            ps1.setString(1, user.getUsername());
            ps1.setString(2, user.getPassword());
            ps1.setString(3, user.getEmail());
            ps1.setString(4, user.getRole());
            ps1.executeUpdate();
            
            // Get the ID generated by the users table
            ResultSet rs = ps1.getGeneratedKeys();
            int newUserId = -1;
            if(rs.next()) {
                newUserId = rs.getInt(1);
            } else {
                throw new SQLException("Failed to retrieve generated user ID.");
            }
            
            // 2. Insert into JOBSEEKERS or EMPLOYERS table
            String sql2;
            if (user instanceof Employer) {
                sql2 = "INSERT INTO employers (user_id, company_name) VALUES (?, ?)";
            } else if (user instanceof JobSeeker) {
                sql2 = "INSERT INTO jobseekers (user_id, resume) VALUES (?, ?)";
            } else {
                 throw new SQLException("Invalid user role specified.");
            }
            
            ps2 = con.prepareStatement(sql2);
            ps2.setInt(1, newUserId);
            ps2.setString(2, detail); 
            ps2.executeUpdate();
            
            con.commit(); // **COMMIT TRANSACTION**
            return true;

        } catch (SQLException e) {
            if(con != null) {
                try {
                    con.rollback(); // **ROLLBACK TRANSACTION** on error
                } catch(SQLException ex) {
                    System.err.println("Rollback failed: " + ex.getMessage());
                }
            }
            throw e; // Re-throw the original exception
            
        } finally {
            try { if(ps1 != null) ps1.close(); } catch(SQLException ignored) {}
            try { if(ps2 != null) ps2.close(); } catch(SQLException ignored) {}
            try { if(con != null) con.close(); } catch(SQLException ignored) {}
        }
    }
}

