
package com.example.jobportal.servlets;

import com.example.jobportal.dao.UserDAO;
import com.example.jobportal.model.Employer;
import com.example.jobportal.model.JobSeeker;
import com.example.jobportal.model.User;
import java.io.IOException;
import java.sql.SQLException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/register")
public class RegisterServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        // 1. Gather common user parameters
        String username = request.getParameter("username");
        String password = request.getParameter("password");
        String email = request.getParameter("email");
        String role = request.getParameter("role");

        User newUser = null;
        String detail = null; // Holds companyName or resume link

        // 2. Polymorphism and Inheritance: Instantiate the correct subclass
        if ("employer".equals(role)) {
            String companyName = request.getParameter("companyName");
            // Constructor: id=0 (will be generated by DB), username, password, email, companyName
            newUser = new Employer(0, username, password, email, companyName);
            detail = companyName;
        } else if ("jobseeker".equals(role)) {
            String resume = request.getParameter("resume");
            // Constructor: id=0, username, password, email, resume
            newUser = new JobSeeker(0, username, password, email, resume);
            detail = resume;
        } else {
            // Handle error if role is missing or invalid
            request.setAttribute("message", "Error: Invalid user role selected.");
            request.getRequestDispatcher("jsp/register.jsp").forward(request, response);
            return; 
        }

        // 3. Call DAO layer for Transactional Database Insertion
        try {
            boolean success = UserDAO.registerUser(newUser, detail);

            if (success) {
                // Success: Redirect to login page
                response.sendRedirect("jsp/login.jsp?registered=true");
            } else {
                // Should theoretically be caught by SQLException, but added for completeness
                request.setAttribute("message", "Registration failed due to unknown database error.");
                request.getRequestDispatcher("jsp/register.jsp").forward(request, response);
            }
        } catch (SQLException e) {
            // Error Handling: Catch potential JDBC issues (e.g., duplicate username, connection failure)
            String errorMessage;
            if (e.getMessage().contains("Duplicate entry")) {
                errorMessage = "Registration failed: Username or Email already exists.";
            } else {
                // Generic database error
                errorMessage = "A critical database error occurred during registration. Please try again.";
                e.printStackTrace(); // Print stack trace for debugging
            }
            
            request.setAttribute("message", errorMessage);
            request.getRequestDispatcher("jsp/register.jsp").forward(request, response);
        }
    }
}